// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getBillingMeter(args?: GetBillingMeterArgs, opts?: pulumi.InvokeOptions): Promise<GetBillingMeterResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("stripe:index/getBillingMeter:getBillingMeter", {
        "eventName": args.eventName,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getBillingMeter.
 */
export interface GetBillingMeterArgs {
    eventName?: string;
    id?: string;
}

/**
 * A collection of values returned by getBillingMeter.
 */
export interface GetBillingMeterResult {
    readonly displayName: string;
    readonly eventName: string;
    readonly id: string;
    readonly status: string;
}
export function getBillingMeterOutput(args?: GetBillingMeterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBillingMeterResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("stripe:index/getBillingMeter:getBillingMeter", {
        "eventName": args.eventName,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getBillingMeter.
 */
export interface GetBillingMeterOutputArgs {
    eventName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
}
